/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenerationsRouteImport } from './routes/generations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiGenerationsIdImageRouteImport } from './routes/api/generations/$id/image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsRoute = GenerationsRouteImport.update({
  id: '/generations',
  path: '/generations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/settings/providers',
  path: '/settings/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerationsIdImageRoute = ApiGenerationsIdImageRouteImport.update({
  id: '/api/generations/$id/image',
  path: '/api/generations/$id/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generations': typeof GenerationsRoute
  '/login': typeof LoginRoute
  '/usage': typeof UsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/generations/$id/image': typeof ApiGenerationsIdImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generations': typeof GenerationsRoute
  '/login': typeof LoginRoute
  '/usage': typeof UsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/generations/$id/image': typeof ApiGenerationsIdImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generations': typeof GenerationsRoute
  '/login': typeof LoginRoute
  '/usage': typeof UsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/generations/$id/image': typeof ApiGenerationsIdImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/generations'
    | '/login'
    | '/usage'
    | '/admin/users'
    | '/settings/api-keys'
    | '/settings/providers'
    | '/api/auth/$'
    | '/api/generations/$id/image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generations'
    | '/login'
    | '/usage'
    | '/admin/users'
    | '/settings/api-keys'
    | '/settings/providers'
    | '/api/auth/$'
    | '/api/generations/$id/image'
  id:
    | '__root__'
    | '/'
    | '/generations'
    | '/login'
    | '/usage'
    | '/admin/users'
    | '/settings/api-keys'
    | '/settings/providers'
    | '/api/auth/$'
    | '/api/generations/$id/image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerationsRoute: typeof GenerationsRoute
  LoginRoute: typeof LoginRoute
  UsageRoute: typeof UsageRoute
  AdminUsersRoute: typeof AdminUsersRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGenerationsIdImageRoute: typeof ApiGenerationsIdImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations': {
      id: '/generations'
      path: '/generations'
      fullPath: '/generations'
      preLoaderRoute: typeof GenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/settings/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generations/$id/image': {
      id: '/api/generations/$id/image'
      path: '/api/generations/$id/image'
      fullPath: '/api/generations/$id/image'
      preLoaderRoute: typeof ApiGenerationsIdImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerationsRoute: GenerationsRoute,
  LoginRoute: LoginRoute,
  UsageRoute: UsageRoute,
  AdminUsersRoute: AdminUsersRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGenerationsIdImageRoute: ApiGenerationsIdImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
