/**
 * The shape of the committed catalogue in `data/`.
 *
 * Both files are generated by `bun run data:sync` from the MLBB Fandom wiki's Lua
 * data modules — nothing here is hand-edited, and a field only exists if the wiki
 * actually carries it. English names throughout: the wiki has no Vietnamese ones,
 * and inventing them would be worse than leaving them.
 */

export const ROLES = [
	"Tank",
	"Fighter",
	"Assassin",
	"Mage",
	"Marksman",
	"Support",
] as const;
export type Role = (typeof ROLES)[number];

export const LANES = [
	"EXP Lane",
	"Gold Lane",
	"Mid Lane",
	"Jungle",
	"Roaming",
] as const;
export type Lane = (typeof LANES)[number];

/** Rarity, weakest first. The wiki leaves it empty for a hero's default skin. */
export const TIERS = [
	"Common",
	"Exceptional",
	"Deluxe",
	"Exquisite",
	"Grand",
	"Supreme",
] as const;
export type Tier = (typeof TIERS)[number];

export const AVAILABILITY = ["Available", "Limited", "Upcoming"] as const;
export type Availability = (typeof AVAILABILITY)[number];

/** What a thing costs, by currency. Absent means "not sold for that currency". */
export interface Price {
	/** Diamonds. */
	dm?: number;
	/** Battle points. */
	bp?: number;
	/** Tickets. */
	ticket?: number;
	/** Hero / skin fragments. */
	fragment?: number;
	/** Lucky gems. */
	lg?: number;
	/** Everything the wiki records as prose: "M5 Pass", "Zodiac Summon", … */
	other?: string;
}

export interface Hero {
	/** Wiki id, and the stem of its default skin's icon file. Unique. */
	id: string;
	/** Release order, 1-based. */
	number: number;
	name: string;
	/** The hero's own epithet — "Energy Gunner" for Layla. Not a skin. */
	title: string;
	roles: Role[];
	lanes: Lane[];
	/** In-world origin: Eruditio, Moniyan Empire, … Empty when the wiki has none. */
	region: string;
	releaseYear: number | null;
	price: Price;
	/** Wikia CDN path segment, joined onto `CDN` in `images.ts`. */
	icon: string;
	/** Full-bleed art for the default skin. Null for the few the wiki lacks. */
	splash: string | null;
}

export interface Skin {
	/** Wiki id, and the stem of its icon file. Unique across all heroes. */
	id: string;
	/** `Hero.name` — the join key. */
	hero: string;
	name: string;
	/** Empty string for a hero's default skin, which has no rarity. */
	tier: Tier | "";
	/** Collection or event it belongs to: StarLight, Collector, M5, KOF, … */
	tag: string;
	availability: Availability;
	/** As the wiki writes it, e.g. `2016-XX-XX` — the day is often unknown. */
	release: string;
	price: Price;
	icon: string;
	splash: string | null;
}

/** Written by the sync script so a stale dataset is visible rather than silent. */
export interface CatalogueMeta {
	syncedAt: string;
	heroes: number;
	skins: number;
	source: string;
}
